# This is an upstream repository intended to be used as a common-repo by
# downstream consumers
- self:
    - repo:
        url: https://github.com/common-repo/upstream
        ref: v2.1.2
        with:
        - template-vars:
            GH_APP_ID_SECRET: COMMON_REPO_BOT_CLIENT_ID
            GH_APP_KEY_SECRET: COMMON_REPO_BOT_PRIVATE_KEY
            GH_APP_OWNER: common-repo

# Include everything in src/, rename it into the root, and flag
# .pre-commit-config.yaml for merging
- include: ["src/**"]
- rename:
    - "^src/(.*)$": "$1"
- yaml:
    auto-merge: .pre-commit-config.yaml
    array_mode: append_unique
